import Header from '../components/Header'
import Footer from '../components/Footer'
// import UserContext from '../contexts/UserContext'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      {/* <UserContext.Provider > */}
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      {/* </UserContext.Provider> */}
    </html>
  )
}
