"""empty message

Revision ID: 053a7e0fdc6c
Revises: 3dfcfd513742
Create Date: 2023-08-28 22:22:56.639738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053a7e0fdc6c'
down_revision = '3dfcfd513742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_species')),
    sa.UniqueConstraint('name', name=op.f('uq_species_name'))
    )
    op.create_table('pet_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('happiness', sa.Integer(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('hunger', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_pet_states_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pet_states'))
    )
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.drop_constraint('uq_owners_user_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_owners_username'), ['username'])
        batch_op.drop_constraint('fk_owners_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_owner_id_owners'), 'owners', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_owner_id_owners'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_owners_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_owners_username'), type_='unique')
        batch_op.create_unique_constraint('uq_owners_user_id', ['user_id'])
        batch_op.drop_column('username')

    op.drop_table('pet_states')
    op.drop_table('species')
    # ### end Alembic commands ###
