"""empty message

Revision ID: 28341c538588
Revises: fc85b87c0da5
Create Date: 2023-08-29 01:31:58.161876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28341c538588'
down_revision = 'fc85b87c0da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_owners_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_owner_id_owners', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_users_owner_id_owners', 'owners', ['owner_id'], ['id'])

    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_owners_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
