"""empty message

Revision ID: 2a1f9a30dfbf
Revises: d0c33fa11357
Create Date: 2023-08-28 22:52:06.270515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1f9a30dfbf'
down_revision = 'd0c33fa11357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_constraint('uq_owners_username', type_='unique')
        batch_op.drop_column('username')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_owner_id_owners', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_users_owner_id_owners', 'owners', ['owner_id'], ['id'])

    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.create_unique_constraint('uq_owners_username', ['username'])

    # ### end Alembic commands ###
