"""empty message

Revision ID: d0c33fa11357
Revises: 1dd7e3f1c7f2
Create Date: 2023-08-28 22:48:39.517168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c33fa11357'
down_revision = '1dd7e3f1c7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_owners')
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.drop_constraint('uq_owners_user_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_owners_username'), ['username'])
        batch_op.drop_constraint('fk_owners_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_owner_id_owners'), 'owners', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_owner_id_owners'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_owners_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_owners_username'), type_='unique')
        batch_op.create_unique_constraint('uq_owners_user_id', ['user_id'])
        batch_op.drop_column('username')

    op.create_table('_alembic_tmp_owners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('avatar', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('bio', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_owners'),
    sa.UniqueConstraint('username', name='uq_owners_username')
    )
    # ### end Alembic commands ###
