"""empty message

Revision ID: d610f1c7a345
Revises: 28341c538588
Create Date: 2023-08-29 15:23:35.870520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd610f1c7a345'
down_revision = '28341c538588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_constraint('uq_pets_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_pets_name', ['name'])

    # ### end Alembic commands ###
